### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by hmkim** [bioinf-mcb/gisaid-scrapper#20]
<img width="812" alt="스크린샷 2020-04-06 오전 9 31 05" src="https://user-images.githubusercontent.com/4966343/78513909-a787c680-77e9-11ea-95ec-66bd246f2adc.png">

If '/' in the filename, the destination was confused.

Please check this issue.

Thank you in advance!

**Comment by hans49732563** [comment]
I solved this problem by change "name = row.find_elements_by_tag_name("td")[2].text" to "name = row.find_elements_by_tag_name("td")[3].text" in gisaid_scrapper.py.
