### ISSUE TITLE
Element is stale

### ISSUE THREAD

**Issue by IvoLeist** [bioinf-mcb/gisaid-scrapper#5]
Hello,

thank you for making your scraper public. 
Unfortunately it runs after downloading one sample in the issue below:

> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <td id="yui-gen79" class="yui-dt0-col-d yui-dt-col-d yui-dt-sortable yui-dt-resizeable"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

Arch Linux
Python 3.7.6 | packaged by conda-forge | (default, Mar  5 2020, 15:27:18)
geckodriver 0.26.0
Mozilla Firefox 74.0

**Comment by wwydmanski** [comment]
Please check if the newest version fixed that

**Comment by IvoLeist** [comment]
I did not run all samples since we in the end used another scraper to get all the data
but just for the record the error happening before seems to be fixed.
